#!/bin/bash
# Author: Walter Paulo
# Email: walter0paulo@hotmail.com
# Data: 2022-4-16
# Abrir programa Spring Tools 4

echo "Iniciando Spring Tools 4..."
/opt/sts-4.15.3.RELEASE/SpringToolSuite4 > /dev/null 2>&1 &
echo "PROCESSO: "$$


